@echo off
if not exist "build/" mkdir build
cd build

rem wgvk
rem cmake .. -GNinja -DRAYGPU_BUILD_SHARED_LIBRARY=ON -DSUPPORT_GLFW=ON -DSUPPORT_WGSL_PARSER=ON -DSUPPORT_TINT_WGSL_PARSER=ON -DSUPPORT_WGPU_BACKEND=OFF -DSUPPORT_VULKAN_BACKEND=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-msse3" -DCMAKE_CXX_FLAGS="-msse3" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON

rem dawn

set BUILD_TYPE=RelWithDebInfo

cmake .. -GNinja ^
    -DRAYGPU_BUILD_SHARED_LIBRARY=ON ^
    -DSUPPORT_GLFW=ON ^
    -DSUPPORT_SDL3=OFF ^
    -DSUPPORT_RGFW=OFF ^
    -DSUPPORT_WGSL_PARSER=ON ^
    -DSUPPORT_WGPU_BACKEND=ON ^
    -DSUPPORT_VULKAN_BACKEND=OFF ^
    -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
    -DCMAKE_C_FLAGS="-msse3" ^
    -DCMAKE_CXX_FLAGS="-msse3" ^
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON

cmake --build . --config %BUILD_TYPE%
cd ..
